### ISSUE TITLE
Getting Plugin WordPress failed error 

### ISSUE THREAD

**Issue by githubMerge** [urbanadventurer/WhatWeb#258]
I am getting following error 
`ERROR: Plugin WordPress failed for http://200.40.113.55:80. URI must be ascii only "http://www.aou.org.uy/wp-content/uploads/Timb\xC3\xB3-Web.jpg"`

```
$ ./whatweb 200.40.113.55:80 --log-json=- -q
[
ERROR: Plugin WordPress failed for http://200.40.113.55:80. URI must be ascii only "http://www.aou.org.uy/wp-content/uploads/Timb\xC3\xB3-Web.jpg"
{"target":"http://200.40.113.55:80","http_status":200,"request_config":{"headers":{"User-Agent":"WhatWeb/0.4.9"}},"plugins":{"PHP":{"version":["5.3.3"]},"Email":{"string":["contactoaou@aou.org.uy"]},"Country":{"string":["URUGUAY"],"module":["UY"]},"JQuery":{"version":["1.12.3"]},"UncommonHeaders":{"string":["link"]},"IP":{"string":["200.40.113.55"]},"Apache":{"version":["2.2.15"]},"Google-Analytics":{"version":["Universal"],"account":["UA-66389411-1"]},"X-Powered-By":{"string":["PHP/5.3.3"]},"Script":{"string":["text/javascript"]},"HTML5":{},"HTTPServer":{"os":["CentOS"],"string":["Apache/2.2.15 (CentOS)"]},"MetaGenerator":{"string":["WordPress 4.5.2"]}}},
{}
]
```

**Comment by urbanadventurer** [comment]
The WordPress plugin uses the Ruby URI library and it cannot handle this sort of RFC non-compliant URL.

Here are some examples using URI.join and URI.parse.

```
irb(main):023:0> URI.join( "http://www.aou.org.uy/wp-content/uploads/Timb\u00F3-Web.jpg", "/" )
Traceback (most recent call last):
        7: from /home/dc/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        6: from (irb):23
        5: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/common.rb:275:in `join'
        4: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:88:in `join'
        3: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'
        2: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
        1: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:21:in `split'
URI::InvalidURIError (URI must be ascii only "http://www.aou.org.uy/wp-content/uploads/Timb\u00F3-Web.jpg")
irb(main):024:0> 
irb(main):025:0> URI.parse( "http://www.aou.org.uy/wp-content/uploads/Timb\u00F3-Web.jpg")
Traceback (most recent call last):
        5: from /home/dc/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        4: from (irb):25
        3: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
        2: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
        1: from /home/dc/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:21:in `split'
URI::InvalidURIError (URI must be ascii only "http://www.aou.org.uy/wp-content/uploads/Timb\u00F3-Web.jpg")
```

Here is the debug output with a traceback.

```
 ./whatweb --debug http://200.40.113.55:80
ERROR: Plugin WordPress failed for http://200.40.113.55:80. URI must be ascii only "http://www.aou.org.uy/wp-content/uploads/Timb\u00F3-Web.jpg"
#<Thread:0x000055eabb6eb4b8@/home/-/projects/WhatWeb/lib/whatweb/scan.rb:41 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	18: from /home/-/projects/WhatWeb/lib/whatweb/scan.rb:43:in `block (2 levels) in scan'
	17: from /home/-/projects/WhatWeb/lib/whatweb/scan.rb:43:in `loop'
	16: from /home/-/projects/WhatWeb/lib/whatweb/scan.rb:57:in `block (3 levels) in scan'
	15: from ./whatweb:653:in `block in <main>'
	14: from /home/-/projects/WhatWeb/lib/whatweb/parser.rb:25:in `run_plugins'
	13: from /home/-/projects/WhatWeb/lib/whatweb/parser.rb:25:in `each'
	12: from /home/-/projects/WhatWeb/lib/whatweb/parser.rb:29:in `block in run_plugins'
	11: from /home/-/projects/WhatWeb/lib/plugins.rb:80:in `scan'
	10: from /home/-/projects/WhatWeb/lib/plugins.rb:250:in `x'
	 9: from /home/-/projects/WhatWeb/plugins/wordpress.rb:66:in `block (2 levels) in <top (required)>'
	 8: from /home/-/projects/WhatWeb/plugins/wordpress.rb:66:in `each'
	 7: from /home/-/projects/WhatWeb/plugins/wordpress.rb:68:in `block (3 levels) in <top (required)>'
	 6: from /home/-/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/common.rb:275:in `join'
	 5: from /home/-/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:89:in `join'
	 4: from /home/-/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:89:in `inject'
	 3: from /home/-/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/generic.rb:1101:in `merge'
	 2: from /home/-/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'
	 1: from /home/-/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/home/-/.rbenv/versions/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "http://www.aou.org.uy/wp-content/uploads/Timb\u00F3-Web.jpg" (URI::InvalidURIError)
```

**Comment by urbanadventurer** [comment]
This isn't really a bug in WhatWeb's engine or in the WordPress plugin. What behaviour would you expect?

**Comment by urbanadventurer** [comment]
Are you happy for me to close this issue?

**Comment by githubMerge** [comment]
Yes.
