### ISSUE TITLE
unit test broken

### ISSUE THREAD

**Issue by oregonpillow** [urbanadventurer/WhatWeb#402]
The unit test uses `http://whatweb.net` as a target, but this site is no longer resolves to anything.

```
Run options: --seed 21074

# Running:

...#<Thread:0x0000000113e94d78 /Users/vader/WhatWeb/lib/whatweb/scan.rb:41 run> terminated with exception (report_on_exception is true):
/Users/vader/WhatWeb/lib/whatweb/scan.rb:52:in `rescue in block (3 levels) in scan': undefined method `error' for #<WhatWeb::Scan:0x0000000113e960b0 @targets=["http://whatweb.net"], @max_threads=25, @target_queue=#<Thread::Queue:0x0000000113e95548>> (NoMethodError)

              error("ERROR Opening: #{target} - #{e}")
              ^^^^^
	from /Users/vader/WhatWeb/lib/whatweb/scan.rb:49:in `block (3 levels) in scan'
	from /Users/vader/WhatWeb/lib/whatweb/scan.rb:43:in `loop'
	from /Users/vader/WhatWeb/lib/whatweb/scan.rb:43:in `block (2 levels) in scan'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/resolv-replace.rb:25:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/resolv-replace.rb:25:in `initialize'
	from /Users/vader/WhatWeb/lib/extend-http.rb:77:in `open'
	from /Users/vader/WhatWeb/lib/extend-http.rb:77:in `block in connect'
	from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
	from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/timeout.rb:196:in `timeout'
	from /Users/vader/WhatWeb/lib/extend-http.rb:76:in `connect'
	from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
	from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/net/http.rb:1237:in `start'
	from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/net/http.rb:1817:in `request'
	from /Users/vader/WhatWeb/lib/target.rb:307:in `open_url'
	from /Users/vader/WhatWeb/lib/target.rb:210:in `open'
	from /Users/vader/WhatWeb/lib/whatweb/scan.rb:50:in `block (3 levels) in scan'
	from /Users/vader/WhatWeb/lib/whatweb/scan.rb:43:in `loop'
	from /Users/vader/WhatWeb/lib/whatweb/scan.rb:43:in `block (2 levels) in scan'
E.

Finished in 17.449755s, 0.2865 runs/s, 0.7450 assertions/s.

  1) Error:
WhatWebTest#test_scan:
NoMethodError: undefined method `error' for #<WhatWeb::Scan:0x0000000113e960b0 @targets=["http://whatweb.net"], @max_threads=25, @target_queue=#<Thread::Queue:0x0000000113e95548>>
    /Users/vader/WhatWeb/lib/whatweb/scan.rb:52:in `rescue in block (3 levels) in scan'
    /Users/vader/WhatWeb/lib/whatweb/scan.rb:49:in `block (3 levels) in scan'
    /Users/vader/WhatWeb/lib/whatweb/scan.rb:43:in `loop'
    /Users/vader/WhatWeb/lib/whatweb/scan.rb:43:in `block (2 levels) in scan'

5 runs, 13 assertions, 0 failures, 1 errors, 0 skips

```

**Comment by bcoles** [comment]
Ah yeah that's my bad. `whatweb.net` has been offline for a while. It is back now.
