### ISSUE TITLE
rcharset gem dependency used by Charset plugin fails with ruby1.9.1

### ISSUE THREAD

**Issue by urbanadventurer** [urbanadventurer/WhatWeb#88]
ruby1.9.1 ./whatweb -p +plugins-disabled/Charset.rb  http://r25.yahoo.co.jp/fushigi/rxr_detail/?id=20120920-00026223-r25
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/rchardet-1.3/lib/rchardet/chardistribution.rb:60: syntax error, unexpected ':', expecting keyword_then or ';' or '\n' (SyntaxError)
/var/lib/gems/1.9.1/gems/rchardet-1.3/lib/rchardet/chardistribution.rb:61: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/var/lib/gems/1.9.1/gems/rchardet-1.3/lib/rchardet/chardistribution.rb:75: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/var/lib/gems/1.9.1/gems/rchardet-1.3/lib/rchardet/chardistribution.rb:84: syntax error, unexpected keyword_end, expecting $end
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/rchardet-1.3/lib/rchardet.rb:25:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:59:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from ./whatweb:89:in `block in <main>'
	from ./whatweb:85:in `each'
	from ./whatweb:85:in `<main>'

**Comment by urbanadventurer** [comment]
This issue is fixed with Ruby 2.x and Ruby 1.9.x
