### ISSUE TITLE
non-UTF8 Charsets fail to display, and convert to UTF-8

### ISSUE THREAD

**Issue by urbanadventurer** [urbanadventurer/WhatWeb#92]
Whatweb currently expects all websites to be UTF-8.
Need a new way to detect charsets and convert to UTF-8 properly, if possible.

It fails for Shift_JIS, e.g. www.amazon.co.jp, and some others.

```
http://www.amazon.co.jp [200] Cookies[session-id,session-id-time,skin,x-wl-uid], Country[IRELAND][IE], HTTPServer[Server], IP[176.32.120.142], Script[text/javascript], Title[Amazon.co.jp�F �ʔ� - �t�@�b�V�����A�Ɠd�����H�i�܂Ły�����z���z], UncommonHeaders[x-amz-id-1,x-amz-id-2]

http://www.insee.fr/fr/ [200] Cookies[ASPSESSIONIDAQQTATTD], Country[FRANCE][FR], HTTPServer[Microsoft-IIS/6.0], IP[81.255.68.54], JQuery, Lightbox, Microsoft-IIS[6.0], Script[text/Javascript,text/javascript], Title[Institut national de la statistique et des �tudes �conomiques : Accueil]
```

Additionally, logging to JSON and Mongo will fail. This occurs with Ruby 1.9.x
```
 ruby1.9.1 ./whatweb --debug --custom-plugin "{:version=>/Cornish.*/}" --log-errors e.log --log-json j.log --log-brief b.log --log-xml x.log http://www.columbia.edu/~fdc/utf8/
ERROR Logging failed: http://www.columbia.edu/~fdc/utf8/ - "\xC3" from ASCII-8BIT to UTF-8
/usr/lib/ruby/1.9.1/json/common.rb:216:in `encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /usr/lib/ruby/1.9.1/json/common.rb:216:in `generate'
	from /usr/lib/ruby/1.9.1/json/common.rb:216:in `generate'
	from /home/dc/projects/whatweb/whatweb-new/lib/output.rb:626:in `block in out'
	from <internal:prelude>:10:in `synchronize'
	from /home/dc/projects/whatweb/whatweb-new/lib/output.rb:625:in `out'
	from ./whatweb:960:in `block (2 levels) in <main>'
	from ./whatweb:958:in `each'
	from ./whatweb:958:in `block in <main>'
```

**Comment by urbanadventurer** [comment]
This works now

:~/projects/WhatWeb$ ./whatweb http://www.columbia.edu/~fdc/utf8/
http://www.columbia.edu/~fdc/utf8/ [200] Apache, Cookies[BIGipServer~CUIT~www.columbia.edu-80-pool], Country[UNITED STATES][US], Email[b.dedominicis@cite-sciences.fr,fdc@columbia.edu,kermit@columbia.edu], HTTPServer[Apache], IP[128.59.105.24], Title[UTF-8 Sampler]

:~/projects/WhatWeb$ ./whatweb --debug --custom-plugin "{:version=>/Cornish.*/}" --log-errors e.log --log-json j.log --log-brief b.log --log-xml x.log http://www.columbia.edu/~fdc/utf8/
http://www.columbia.edu/~fdc/utf8/ [200] Apache, Cookies[BIGipServer~CUIT~www.columbia.edu-80-pool], Country[UNITED STATES][US], Custom-Plugin[Cornish:</b> Chris Stephens.,Cornish</b>: Mý a yl dybry gwéder hag éf ny wra ow ankenya.], Email[b.dedominicis@cite-sciences.fr,fdc@columbia.edu,kermit@columbia.edu], HTTPServer[Apache], IP[128.59.105.24], Title[UTF-8 Sampler]
